# Basic Python

In [ ]:
s="Hi there Sam!"


In [9]:
print(s.split())

['Hi', 'there', 'Sam!']


In [14]:
planet = "Earth"
diameter = 12742

In [15]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))


The diameter of Earth is 12742 kilometers.


In [16]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [17]:
s1=d['k1']
d1=s1[3]
s2=d1["tricky"]
d2=s2[3]
s3=d2["target"]
print(s3[3])

hello


# Numpy

In [18]:
import numpy as np


In [29]:
array=np.zeros(10)
print(array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [30]:
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


In [31]:
array=np.arange(0,9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


# Pandas

In [24]:
import pandas as pd

In [25]:
data=[['vijay',12],['ajith',24],['surya',44]]
df=pd.DataFrame(data,columns=['Name','Age'])
print (df)

    Name  Age
0  vijay   12
1  ajith   24
2  surya   44


In [26]:
d=pd.date_range(start='01/01/2023',end='02/10/2023')
print (d)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


In [27]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['T1','T2','T3'])
print (df)

   T1   T2  T3
0   1  aaa  22
1   2  bbb  25
2   3  ccc  24
